---
validators:
  tenseSubject:
    enabled: true
  lineLength:
    enabled: true
    maxLineLength: 72
    subjectMaxLength: 50
  ticketCode:
    enabled: false
  emptyLines:
    enabled: true
    emptyLines: 1
  tags:
    enabled: true
    tags: fix, chore, feature, style, docs
  subjectPeriod:
    enabled: false
  capitalizedSubject:
    enabled: true
  wip:
    enabled: true
    branch: master
