---
Validators.lineLength:
  Enabled: true
  MaxLineLength: 72
  SubjectWarnLength: 50
  AllowLongUrls: true
Validators.tense:
  Enabled: true
Validators.subjectPeriod:
  Enabled: false
Validators.capitalizeSubject:
  Enabled: true
Validators.Wip:
  Enabled:
    - master
