---
validators:
  lineLength:
    enabled: true
    maxLineLength: 72
    subjectWarnLength: 50
    allowLongUrls: true
  tense:
    enabled: true
  subjectPeriod:
    enabled: false
    capitalizeSubject:
    enabled: true
  Wip:
    enabled:
      - master
